spring.application.name=gestionDesTournois
server.port=8091
# DATABASE
spring.datasource.url=jdbc:postgresql://localhost:5432/GestionDesTournois
spring.datasource.username=postgres
spring.datasource.password=wxcvbn

# DRIVER
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / HIBERNATE
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# SHOW SQL (debug)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true